name: fair38
dependencies:
  - python==3.8
  - numpy==1.22.3
  # - gdal
  - pandas==1.4.1
  - setuptools
  # - solaris
  - pip==21.2.4
  - pip:
    # from colab
    - affine==2.3.1
    # Relaxed for solaris
    - albumentations
    - attrs==21.4.0
    - branca==0.4.2
    - brotlipy==0.7.0
    - certifi==2021.10.8
    - cffi==1.15.0
    - charset-normalizer==2.0.4
    - click==8.1.0
    - click-plugins==1.1.1
    - cligj==0.7.2
    - cloudpickle==2.0.0
    - cryptography==36.0.0
    - cycler==0.11.0
    - cython==0.29.32
    - cytoolz==0.11.2
    # Removed for testing env install as not used in src
    # - dask==2022.3.0
    - efficientnet==1.0.0
    - Fiona==1.8.21
    - folium==0.12.1.post1
    - fonttools==4.31.2
    - fsspec==2022.2.0
    # - gdal==3.3.2
    - geojson==2.5.0
    - geopandas==0.10.2
    - h5py==3.6.0
    - idna==3.3
    - image-classifiers==1.0.0
    - imagecodecs
    - imageio==2.16.1
    - imgaug==0.4.0
    - Jinja2==3.1.1
    - joblib==1.1.0
    - Keras-Applications==1.0.8
    - kiwisolver==1.4.2
    - locket==0.2.0
    - mapclassify==2.4.3
    - MarkupSafe==2.1.1
    - matplotlib==3.5.1
    - mercantile==1.2.1
    - munch==2.5.0
    - munkres==1.1.4
    - networkx==2.7.1
    - opencv-python
    - packaging==21.3
    - partd==1.2.0
    - Pillow==9.0.1
    - pycosat==0.6.3
    - pycparser==2.21
    - pyOpenSSL==21.0.0
    - pyparsing==3.0.7
    - pyproj
    - PySocks==1.7.1
    - python-dateutil==2.8.2
    - pytz==2022.1
    - PyWavelets==1.3.0
    # - PyYAML==6.0
    # Relaxed for solaris
    - PyYAML
    - rasterio
    # Relaxed for solaris
    - requests
    - Rtree==0.9.7
    - scikit-fmm==2022.8.15
    - scikit-image==0.19.2
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - segmentation-models==1.0.1
    - setuptools==58.0.4
    - Shapely==1.8.0
    - six==1.16.0
    - snuggs==1.4.7
    # Only used for ramp-code but deps on tf 1.13.1 which is too old so not using here, can use keras instead for the IOU
    # - solaris==0.4.0
    - threadpoolctl==3.1.0
    - tifffile
    - tinydb==4.7.0
    - toolz==0.11.2
    - tqdm==4.62.3
    - unicodedata2==14.0.0
    - urllib3==1.26.7
    - wheel==0.37.1
    - xyzservices==2022.3.0
# from solaris
    # - torch
    # - torchvision
    - tensorflow==2.9.2
    # - tensorflow-macos
    # - tensorflow-metal
# from the makefile
    