name: Check Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Remove solaris
        run: sudo rm -rf ./docker ./weights

      - name: Clone Ramp
        run: git clone https://github.com/kshitijrajsharma/ramp-code-fAIr.git ramp-code

      - name: Install gdown
        run: pip install gdown

      - name: Download Basemodel
        run: gdown --fuzzy https://drive.google.com/file/d/1YQsY61S_rGfJ_f6kLQq4ouYE2l3iRe1k/view?usp=sharing

      - name: Unzip and Move Basemodel
        run: unzip checkpoint.tf.zip -d ramp-code/ramp

      - name: Install gdal
        run: |
          sudo apt-get update && sudo apt-get -y install gdal-bin libgdal-dev python3-gdal && sudo apt-get -y autoremove && sudo apt-get clean
          pip install GDAL==$(gdal-config --version)

      - name: Install ramp dependecies
        run: |
          cd ramp-code && cd colab && make install
      - name: Navigate to home dir
        run: |
          cd ../.. 
          ls
      - name: Install tensorflow
        run: pip install tensorflow==2.9.2

      - name : Install pytorch and ultralytics
        run: pip install torch==2.4.0 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113 ultralytics==8.1.6

      - name: Install fair utilities
        run: pip install -e .

      - name: Run test ramp
        run: |
          pip uninstall -y gdal
          pip install numpy
          pip install GDAL==$(gdal-config --version) --global-option=build_ext --global-option="-I/usr/include/gdal"
          python test_ramp.py

      - name : Run test yolo
        run : |
          python test_yolo_v1.py
          python test_yolo_v2.py

